package route

import (
	"ecommerce-be/fulfillment/factory/singleton"
	"ecommerce-be/fulfillment/handler"

	"github.com/gin-gonic/gin"
)

// WebhookModule implements the Module interface for the public courier
// push endpoint. No auth: the signature is the auth (verified inside).
// Correlation id is generated by middleware (skip rules).
type WebhookModule struct {
	webhookHandler *handler.WebhookHandler
}

// NewWebhookModule creates a new WebhookModule.
func NewWebhookModule() *WebhookModule {
	f := singleton.GetInstance()
	return &WebhookModule{
		webhookHandler: f.GetHandlerFactory().GetWebhookHandler(),
	}
}

// RegisterRoutes registers the public webhook route.
func (m *WebhookModule) RegisterRoutes(router *gin.Engine) {
	router.POST("/api/fulfillment/webhooks/:code", m.webhookHandler.ReceiveWebhook)
}
