package constant

const (
	PAYMENT_GATEWAY_NOT_FOUND_CODE     = "PAYMENT_GATEWAY_NOT_FOUND"
	PAYMENT_GATEWAY_NOT_ACTIVE_CODE    = "PAYMENT_GATEWAY_NOT_ACTIVE"
	PAYMENT_GATEWAY_NOT_SUPPORTED_CODE = "PAYMENT_GATEWAY_NOT_SUPPORTED"

	PAYMENT_TRANSACTION_NOT_FOUND_CODE = "PAYMENT_TRANSACTION_NOT_FOUND"
	PAYMENT_ORDER_NOT_FOUND_CODE       = "PAYMENT_ORDER_NOT_FOUND"
	REFUND_NOT_FOUND_CODE              = "REFUND_NOT_FOUND"
	DUPLICATE_PAYMENT_CODE             = "DUPLICATE_PAYMENT"
	GATEWAY_VALIDATION_CODE            = "GATEWAY_VALIDATION"
	INVALID_WEBHOOK_SIGNATURE_CODE     = "INVALID_WEBHOOK_SIGNATURE"
	DUPLICATE_WEBHOOK_CODE             = "DUPLICATE_WEBHOOK"
	REFUND_NOT_ALLOWED_CODE            = "REFUND_NOT_ALLOWED"
	GATEWAY_NOT_CONFIGURED_CODE        = "GATEWAY_NOT_CONFIGURED"
	GATEWAY_UNSUPPORTED_CURRENCY_CODE  = "GATEWAY_UNSUPPORTED_CURRENCY"
)
