package constant

const (
	PAYMENT_GATEWAY_NOT_FOUND_CODE     = "PAYMENT_GATEWAY_NOT_FOUND"
	PAYMENT_GATEWAY_NOT_ACTIVE_CODE    = "PAYMENT_GATEWAY_NOT_ACTIVE"
	PAYMENT_GATEWAY_NOT_SUPPORTED_CODE = "PAYMENT_GATEWAY_NOT_SUPPORTED"
)
