package constant

// Fulfillment error codes. Secrets and PII never appear in messages.
// Service-design §8; HTTP mapping in api-contracts.md §7.
const (
	FULFILLMENT_NOT_FOUND_CODE               = "FULFILLMENT_NOT_FOUND"
	FULFILLMENT_INVALID_STATE_CODE           = "FULFILLMENT_INVALID_STATE"
	FULFILLMENT_PROVIDER_NOT_SUPPORTED_CODE  = "FULFILLMENT_PROVIDER_NOT_SUPPORTED"
	FULFILLMENT_PROVIDER_NOT_CONFIGURED_CODE = "FULFILLMENT_PROVIDER_NOT_CONFIGURED"
	FULFILLMENT_CREDENTIALS_INVALID_CODE     = "FULFILLMENT_CREDENTIALS_INVALID"
	FULFILLMENT_ENCRYPTION_KEY_MISSING_CODE  = "FULFILLMENT_ENCRYPTION_KEY_MISSING"
	FULFILLMENT_RATE_FAILED_CODE             = "FULFILLMENT_RATE_FAILED"
	FULFILLMENT_BOOK_FAILED_CODE             = "FULFILLMENT_BOOK_FAILED"
	FULFILLMENT_LABEL_FAILED_CODE            = "FULFILLMENT_LABEL_FAILED"
	FULFILLMENT_CAPABILITY_UNSUPPORTED_CODE  = "FULFILLMENT_CAPABILITY_UNSUPPORTED"
	FULFILLMENT_WEBHOOK_UNVERIFIED_CODE      = "FULFILLMENT_WEBHOOK_UNVERIFIED"
	FULFILLMENT_APPLY_MISMATCH_CODE          = "FULFILLMENT_APPLY_MISMATCH"
	FULFILLMENT_STOCK_MISMATCH_CODE          = "FULFILLMENT_STOCK_MISMATCH"
	FULFILLMENT_WEIGHT_REQUIRED_CODE         = "FULFILLMENT_WEIGHT_REQUIRED"
	FULFILLMENT_ADDRESS_CHANGED_CODE         = "FULFILLMENT_ADDRESS_CHANGED"
	FULFILLMENT_AUTO_BOOK_AMBIGUOUS_CODE     = "FULFILLMENT_AUTO_BOOK_AMBIGUOUS"
	FULFILLMENT_RATE_LIMITED_CODE            = "FULFILLMENT_RATE_LIMITED"
)

// Courier codes (factory registry keys).
const (
	COURIER_CODE_SHIPROCKET = "shiprocket"
)

// Shipment statuses — the single vocabulary (data-model §2a).
const (
	SHIPMENT_STATUS_DRAFT            = "draft"
	SHIPMENT_STATUS_BOOKED           = "booked"
	SHIPMENT_STATUS_PICKUP_SCHEDULED = "pickup_scheduled"
	SHIPMENT_STATUS_PICKED           = "picked"
	SHIPMENT_STATUS_IN_TRANSIT       = "in_transit"
	SHIPMENT_STATUS_OUT_FOR_DELIVERY = "out_for_delivery"
	SHIPMENT_STATUS_NDR_PENDING      = "ndr_pending"
	SHIPMENT_STATUS_DELIVERED        = "delivered"
	SHIPMENT_STATUS_FAILED           = "failed"
	SHIPMENT_STATUS_CANCELLED        = "cancelled"
	SHIPMENT_STATUS_RTO_IN_TRANSIT   = "rto_in_transit"
	SHIPMENT_STATUS_RETURNED         = "returned"
)

// Webhook log statuses.
const (
	WEBHOOK_STATUS_RECEIVED = "received"
	WEBHOOK_STATUS_APPLIED  = "applied"
	WEBHOOK_STATUS_FAILED   = "failed"
	WEBHOOK_STATUS_IGNORED  = "ignored"
)

// Event sources (mirrors payment transaction events).
const (
	EVENT_SOURCE_API     = "api"
	EVENT_SOURCE_WEBHOOK = "webhook"
	EVENT_SOURCE_SYSTEM  = "system"
	EVENT_SOURCE_ADMIN   = "admin"
)

// Rate preference values (tenant auto-book).
const (
	RATE_PREFERENCE_CHEAPEST = "cheapest"
	RATE_PREFERENCE_FASTEST  = "fastest"
)
