package constant

// Location error codes
const (
	LOCATION_NOT_FOUND_CODE           = "LOC_NOT_FOUND"
	DUPLICATE_LOCATION_NAME_CODE      = "DUPLICATE_LOC_NAME"
	INVALID_LOCATION_TYPE_CODE        = "INVALID_LOC_TYPE"
	LOCATION_INACTIVE_CODE            = "LOCATION_INACTIVE"
	UNAUTHORIZED_LOCATION_ACCESS_CODE = "UNAUTHORIZED_LOC_ACCESS"
)
