package constant

// Location error codes
const (
	LOCATION_NOT_FOUND_CODE           = "LOC_NOT_FOUND"
	DUPLICATE_LOCATION_NAME_CODE      = "DUPLICATE_LOC_NAME"
	INVALID_LOCATION_TYPE_CODE        = "INVALID_LOC_TYPE"
	LOCATION_INACTIVE_CODE            = "LOCATION_INACTIVE"
	UNAUTHORIZED_LOCATION_ACCESS_CODE = "UNAUTHORIZED_LOC_ACCESS"
)

// Inventory error codes
const (
	INVENTORY_NOT_FOUND_CODE         = "INV_NOT_FOUND"
	PRODUCT_INVENTORY_NOT_FOUND_CODE = "PROD_INV_NOT_FOUND"
	INSUFFICIENT_STOCK_CODE          = "INSUFFICIENT_STOCK"
	INVALID_QUANTITY_CODE            = "INVALID_QUANTITY"
	NEGATIVE_STOCK_CODE              = "NEGATIVE_STOCK"
	BELOW_THRESHOLD_CODE             = "BELOW_THRESHOLD"
	INSUFFICIENT_RESERVED_STOCK_CODE = "INSUFFICIENT_RESERVED_STOCK"
	VARIANT_NOT_FOUND_CODE           = "VAR_NOT_FOUND"
	INVALID_TRANSACTION_TYPE_CODE    = "INVALID_TXN_TYPE"
	INVALID_ADJUSTMENT_TYPE_CODE     = "INVALID_ADJ_TYPE"
	DIRECTION_REQUIRED_CODE          = "DIRECTION_REQUIRED"
	DIRECTION_NOT_ALLOWED_CODE       = "DIRECTION_NOT_ALLOWED"
	NOT_MANUAL_TRANSACTION_CODE      = "NOT_MANUAL_TXN"
	REFERENCE_REQUIRED_CODE          = "REFERENCE_REQUIRED"
)
