package utils

// Category error codes
const (
	CATEGORY_EXISTS_CODE         = "CATEGORY_EXISTS"
	CATEGORY_NOT_FOUND_CODE      = "CATEGORY_NOT_FOUND"
	CATEGORY_HAS_PRODUCTS_CODE   = "CATEGORY_HAS_PRODUCTS"
	CATEGORY_HAS_CHILDREN_CODE   = "CATEGORY_HAS_CHILDREN"
	INVALID_PARENT_CATEGORY_CODE = "INVALID_PARENT_CATEGORY"
	VALIDATION_ERROR_CODE        = "VALIDATION_ERROR"
)

// Attribute Definition error codes
const (
	ATTRIBUTE_DEFINITION_EXISTS_CODE    = "ATTRIBUTE_DEFINITION_EXISTS"
	ATTRIBUTE_DEFINITION_NOT_FOUND_CODE = "ATTRIBUTE_DEFINITION_NOT_FOUND"
	ATTRIBUTE_KEY_EXISTS_CODE           = "ATTRIBUTE_KEY_EXISTS"
	ATTRIBUTE_DATA_TYPE_INVALID_CODE    = "ATTRIBUTE_DATA_TYPE_INVALID"
)

// Product error codes
const (
	PRODUCT_EXISTS_CODE             = "PRODUCT_EXISTS"
	PRODUCT_NOT_FOUND_CODE          = "PRODUCT_NOT_FOUND"
	PRODUCT_SKU_EXISTS_CODE         = "PRODUCT_SKU_EXISTS"
	PRODUCT_CATEGORY_INVALID_CODE   = "PRODUCT_CATEGORY_INVALID"
	PRODUCT_ATTRIBUTES_INVALID_CODE = "PRODUCT_ATTRIBUTES_INVALID"
)

// Package Option error codes
const (
	PACKAGE_OPTION_NOT_FOUND_CODE = "PACKAGE_OPTION_NOT_FOUND"
)
