package utils

// Category error codes
const (
	CATEGORY_EXISTS_CODE              = "CATEGORY_EXISTS"
	CATEGORY_NOT_FOUND_CODE           = "CATEGORY_NOT_FOUND"
	CATEGORY_HAS_PRODUCTS_CODE        = "CATEGORY_HAS_PRODUCTS"
	CATEGORY_HAS_CHILDREN_CODE        = "CATEGORY_HAS_CHILDREN"
	INVALID_PARENT_CATEGORY_CODE      = "INVALID_PARENT_CATEGORY"
	UNAUTHORIZED_CATEGORY_UPDATE_CODE = "UNAUTHORIZED_CATEGORY_UPDATE"
)

// Attribute Definition error codes
const (
	ATTRIBUTE_DEFINITION_EXISTS_CODE    = "ATTRIBUTE_DEFINITION_EXISTS"
	ATTRIBUTE_DEFINITION_NOT_FOUND_CODE = "ATTRIBUTE_DEFINITION_NOT_FOUND"
	ATTRIBUTE_KEY_EXISTS_CODE           = "ATTRIBUTE_KEY_EXISTS"
	ATTRIBUTE_DATA_TYPE_INVALID_CODE    = "ATTRIBUTE_DATA_TYPE_INVALID"
)

// Product error codes
const (
	PRODUCT_EXISTS_CODE             = "PRODUCT_EXISTS"
	PRODUCT_NOT_FOUND_CODE          = "PRODUCT_NOT_FOUND"
	PRODUCT_SKU_EXISTS_CODE         = "PRODUCT_SKU_EXISTS"
	PRODUCT_CATEGORY_INVALID_CODE   = "PRODUCT_CATEGORY_INVALID"
	PRODUCT_ATTRIBUTES_INVALID_CODE = "PRODUCT_ATTRIBUTES_INVALID"
)

// Product Attribute error codes
const (
	PRODUCT_ATTRIBUTE_NOT_FOUND_CODE    = "PRODUCT_ATTRIBUTE_NOT_FOUND"
	PRODUCT_ATTRIBUTE_EXISTS_CODE       = "PRODUCT_ATTRIBUTE_EXISTS"
	INVALID_ATTRIBUTE_VALUE_CODE        = "INVALID_ATTRIBUTE_VALUE"
	UNAUTHORIZED_ATTRIBUTE_ACCESS_CODE  = "UNAUTHORIZED_ATTRIBUTE_ACCESS"
)

// Package Option error codes
const (
	PACKAGE_OPTION_NOT_FOUND_CODE = "PACKAGE_OPTION_NOT_FOUND"
)

// Product Option error codes
const (
	PRODUCT_OPTION_NOT_FOUND_CODE             = "PRODUCT_OPTION_NOT_FOUND"
	PRODUCT_OPTION_NAME_EXISTS_CODE           = "PRODUCT_OPTION_NAME_EXISTS"
	PRODUCT_OPTION_IN_USE_CODE                = "PRODUCT_OPTION_IN_USE"
	PRODUCT_OPTION_VALUE_NOT_FOUND_CODE       = "PRODUCT_OPTION_VALUE_NOT_FOUND"
	PRODUCT_OPTION_VALUE_IN_USE_CODE          = "PRODUCT_OPTION_VALUE_IN_USE"
	PRODUCT_OPTION_VALUE_EXISTS_CODE          = "PRODUCT_OPTION_VALUE_EXISTS"
	PRODUCT_OPTION_PRODUCT_MISMATCH_CODE      = "PRODUCT_OPTION_PRODUCT_MISMATCH"
	PRODUCT_OPTION_VALUE_OPTION_MISMATCH_CODE = "PRODUCT_OPTION_VALUE_OPTION_MISMATCH"
	INVALID_PRODUCT_ID_CODE                   = "INVALID_PRODUCT_ID"
	INVALID_OPTION_ID_CODE                    = "INVALID_OPTION_ID"
	INVALID_OPTION_VALUE_ID_CODE              = "INVALID_OPTION_VALUE_ID"
)

// Variant error codes
const (
	VARIANT_NOT_FOUND_CODE                 = "VARIANT_NOT_FOUND"
	VARIANT_NOT_FOUND_WITH_OPTIONS_CODE    = "VARIANT_NOT_FOUND_WITH_OPTIONS"
	VARIANT_SKU_EXISTS_CODE                = "VARIANT_SKU_EXISTS"
	VARIANT_OPTION_COMBINATION_EXISTS_CODE = "VARIANT_OPTION_COMBINATION_EXISTS"
	INVALID_VARIANT_ID_CODE                = "INVALID_VARIANT_ID"
	INVALID_OPTION_CODE                    = "INVALID_OPTION"
	INVALID_OPTION_VALUE_CODE              = "INVALID_OPTION_VALUE"
	LAST_VARIANT_DELETE_NOT_ALLOWED_CODE   = "LAST_VARIANT_DELETE_NOT_ALLOWED"
	INVALID_STOCK_OPERATION_CODE           = "INVALID_STOCK_OPERATION"
	INSUFFICIENT_STOCK_FOR_OPERATION_CODE  = "INSUFFICIENT_STOCK_FOR_OPERATION"
	BULK_UPDATE_EMPTY_LIST_CODE            = "BULK_UPDATE_EMPTY_LIST"
	BULK_UPDATE_VARIANT_NOT_FOUND_CODE     = "BULK_UPDATE_VARIANT_NOT_FOUND"
)
